source "https://api.berkshelf.com"

cookbook 'apt', github: 'opscode-cookbooks/apt'
cookbook 'chef-solo-search', github: 'edelight/chef-solo-search'
cookbook 'build-essential', github: 'opscode-cookbooks/build-essential'
cookbook 'fail2ban', github: 'opscode-cookbooks/fail2ban'
cookbook 'hostnames', github: 'nathantsoi/chef-cookbook-hostname'
cookbook 'locales', github: 'phbergsmann/chef-locales'
cookbook 'look_and_feel-ctw', github: 'chadwilken/look_and_feel-ctw'
cookbook 'memcached', github: 'opscode-cookbooks/memcached'
cookbook 'mongodb', github: 'edelight/chef-mongodb'
cookbook 'monit-ctw', github: 'chadwilken/monit-ctw', branch: 'master'
cookbook 'monit_configs-ctw', github: 'chadwilken/monit_configs-ctw', branch: 'master'
cookbook 'mysql', github: 'opscode-cookbooks/mysql'
cookbook 'nginx', github: 'miketheman/nginx'
cookbook 'ntp', github: 'gmiranda23/ntp'
cookbook 'openssh', github: 'opscode-cookbooks/openssh'
cookbook 'postgresql', github: 'opscode-cookbooks/postgresql'
cookbook 'rails_gem_dependencies-ctw', github: 'chadwilken/rails_gem_dependencies-ctw'
cookbook 'rbenv', github: 'fnichol/chef-rbenv'
cookbook 'redis-server', github: 'chadwilken/redis-server'
cookbook 'sudo', github: 'opscode-cookbooks/sudo'
cookbook 'ufw', github: 'opscode-cookbooks/ufw'
cookbook 'users', github: 'opscode-cookbooks/users'
